apiVersion: v1
kind: Pod
metadata:
  name: 'api-test-pod'
  labels:
    app: 'api-test-pod'
spec:
  containers:
    - name: api-test-pod
      image: 'ubuntu:latest'
      command:
        - sleep
        - '1000'
      resources:
        limits:
          cpu: 200m
          memory: 500Mi
        requests:
          cpu: 100m
          memory: 200Mi
