apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
  labels:
    app: test-deployment
spec:
  selector:
    matchLabels:
      app: test-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: test-deployment
    spec:
      containers:
        - name: tester
          image: 'ubuntu:latest'
          command:
            - bash
            - -c
            - |
              echo "Falling asleep for $SECS_TO_SLEEP"
              sleep $SECS_TO_SLEEP
          env:
            - name: SECS_TO_SLEEP
              value: '1000'
          resources:
            limits:
              cpu: 200m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 200Mi
# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: test-pod
# spec:
#   containers:
#     - name: tester
#       image: 'ubuntu:latest'
#       command:
#         - sleep
#         - '1000'
#       resources:
#         limits:
#           cpu: 200m
#           memory: 500Mi
#         requests:
#           cpu: 100m
#           memory: 200Mi
