# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package
on:
  release:
    types: [created]
jobs:
  publish-to-github-as-npm:
    name: 'Publish to github as npm package'
    runs-on: ubuntu-latest
    steps:
      - name: 'Read commit args'
        id: args
        uses: LamaAni/parse-commit-args-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'checkout the code'
        uses: actions/checkout@v2

      - name: 'setup nodejs'
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@lamaani'

      - run: |
          echo "Publishing version ${{steps.args.outputs.version}}" &&
          git config --global user.email "actions@no-a-server.com" &&
          git config --global user.name "github actions" &&
          git fetch &&
          git checkout master &&
          npm version '${{steps.args.outputs.version}}' &&
          npm publish && 
          git push origin HEAD
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
